---

- name: Create directories
  file:
    path:   '{{ item.path }}'
    state:  '{{ item.state  | default("directory") }}'
    owner:  '{{ item.owner  | default("root") }}'
    group:  '{{ item.group  | default("root") }}'
    mode:   '{{ item.mode   | default("0755") }}'
  with_items:
    - { path: '/etc/rspamd/conf.d' }
  when: (item.path is defined and item.path)


- name: Configure conf.d
  template:
    src: "etc/rspamd/conf.d/{{ item.type | default('default') }}.conf.j2"
    dest: '/etc/rspamd/conf.d/{{ item.name }}.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items:
    - '{{ rspamd__conf_d }}'
    - '{{ rspamd__conf_d_default }}'
  notify: [ 'rspamd test config' ]

- name: Configure conf.d
  template:
    src: "etc/rspamd/worker-controller.inc.j2"
    dest: '/etc/rspamd/worker-controller.inc'
    owner: 'root'
    group: '_rspamd'
    mode: '0640'
  notify: [ 'rspamd test config' ]

- name: Configure rspamd.conf.local
  template:
    src: "etc/rspamd/rspamd.conf.local.j2"
    dest: '/etc/rspamd/rspamd.conf.local'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'rspamd test config' ]

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
