---

- name: Configure modules
  template:
    src: 'etc/rspamd/modules.d/default.conf.j2'
    dest: '/etc/rspamd/modules.d/{{ item }}.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: [ '{{ rspamd__modules }}' ]
  notify: [ 'rspamd reload' ]

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
